### ISSUE TITLE
C++ exception

### ISSUE THREAD

**Issue by surbhi18** [HyeonwooNoh/DPPnet#3]
I get a C++ exception when I run the vqa_tes.lua in 006_test_DPPNet. Could you help me out?

**Comment by iamaaditya** [comment]
Newer version of torch is not compatible with this project. 

Use the following commit of torch

https://github.com/torch/distro/tree/660bdfea60df0d7c6db690c13ac0c23f13fcb3e7

**Comment by EdwinYam** [comment]
I have already used older version of torch, but I still get a C++ exception when I run the vqa_train.lua in 004_train_DPPnet_fixed_cnn or vqa_tes.lua in 006_test_DPPNet. Could somebody help me? Thx.
(I run torch on Titan X)

**Comment by warahul** [comment]
Hi. Make sure you have nvcc working and older version of torch. Having both these things should solve the c++ exception.
