### ISSUE TITLE
bug in vqa_loader.lua

### ISSUE THREAD

**Issue by warahul** [HyeonwooNoh/DPPnet#4]
Line 1874 "local is_cached = path.isfile(cache_path)" in vqa_loader.lua attempt to index global 'path' (a nil value) as it has not been declared anywhere.

**Comment by HyeonwooNoh** [comment]
You can check the following link.
https://github.com/torch/paths

I guess this module is loaded in default and you could use this module without any declaration.

**Comment by iamaaditya** [comment]
@HyeonwooNoh You may close this issue. @warahul's issue was solved by require 'pl' , although strangely that should not have been required. Perhaps he has different version of Torch.
